server:
  port: 8000
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path : /h2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 62988211500-8vgic0r9i7tmlu0f3h5trbffp3onn4p3.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8000/login/oauth2/code/google
            scope:
              - email
              - profile
jwt:
  issuer: test7206095@gmail.com
  secret_key: study-springboot
